version: '3.7'

services:
#  db:
#    container_name: db
#    image: postgres:10
#    volumes:
#      - ./dbData/:/var/lib/postgresql/data
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=${DB_PASS}
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_DB=${DB_NAME}
#    ports:
#      - ${DB_PORT}:5432

  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
#    environment:
#      DB_HOST: host.docker.internal
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
#    network_mode: host
    container_name: ts-node-docker
#    depends_on:
#      - db
    expose:
      - '4000'
    ports:
      - '4000:4000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: yarn start:dev
